// Manifest of 10 image-gen prompts mirrored from visual xBAZVuPoZv5d.
// Driven by scripts/gen-images.mjs. Edit prompts here, re-run script.
//
// 2026-05-16: P01-P05 previously rendered via Nano Banana 2 — Owner flagged
// gpt-image-2 yields stronger output, so all 10 re-render via this script.
// Statuses below reset to "pending" / "new" to reflect the re-render plan.

export const PROMPTS = [
  {
    id: "P01",
    title: "Hero painterly scene",
    status: "pending",
    size: "2048x1152",
    quality: "high",
    save_path: ".tmp-brand-assets/p01-hero.png",
    prompt: `A vintage natural-history monograph plate in the spirit of Audubon and Thomas Bewick wood engravings. The composition shows a single magpie in mid-flight from left to right, wings spread wide, carrying a small HTML document page in its beak (the page is recognizable as a code-printed sheet with a single line of code visible). Below and to the right, a woven circular nest sits on a hairline ground line, with a single shiny golden bead visible inside it. The bird's plumage is deep ink-black, never pure black. Its right wing carries a single deep cobalt blue patch (#1f2b80). A single mustard-gold dot (#d4a233) sits near the beak as a brand accent. Background is cool stone-paper (#eef0f4), not white. Restrained palette: paper, ink, one cobalt, one gold. No gradients. No glow. No painterly drama. Hairline detail throughout. Craftsmanship register — looks like it took weeks to engrave. Generous negative space top and right. Composition leaves a clear blank zone in the left third for overlay headline text. 16:9 aspect ratio. No decorative elements in any corner. No diamond / gem / sparkle marginalia.`,
  },
  {
    id: "P02",
    title: "Magpie pose variants ×4",
    status: "pending",
    size: "1024x1024",
    quality: "high",
    // {N} expands to pose suffix (01..04). One render per variant.
    save_path: ".tmp-brand-assets/p02-pose-{N}.png",
    pose_variants: [
      { suffix: "01", pose: "takeoff — wings half-raised, feet pushing off a thin branch, beak forward, tail spread for balance" },
      { suffix: "02", pose: "in-flight with HTML page in beak — wings fully spread, carrying a small code-printed paper rectangle" },
      { suffix: "03", pose: "descending — wings tilted, body angled down, head extended toward an unseen target below" },
      { suffix: "04", pose: "landed and perched on nest rim — bird at rest on the rim of an empty woven nest, head turned slightly, alert" },
    ],
    prompt: `A vintage natural-history monograph illustration of a single magpie. [POSE: {POSE}]. Deep ink-black plumage (never pure black). One deep cobalt blue patch (#1f2b80) on the visible wing. One single mustard-gold dot (#d4a233) near the beak as a brand bead. Cool stone-paper background (#eef0f4), not white. No gradients, no glow, no painterly drama. Flat hairline-detailed engraving style in the spirit of Thomas Bewick. Restrained three-color palette: paper, ink, cobalt, gold. Centered subject. 1:1 square composition. Craftsmanship register. No decorative elements in any corner. No diamond / gem / sparkle marginalia. Same bird character across all four images, identical proportions and markings.`,
  },
  {
    id: "P03",
    title: "Nest detail shot",
    status: "pending",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/p03-nest.png",
    prompt: `A vintage natural-history plate showing a top-down view of a circular woven nest, hairline-detailed engraving style. Inside the nest: one prominent mustard-gold shiny bead (#d4a233) at the center, surrounded by three or four small folded paper rectangles representing HTML pages and documents (each paper visible as a small ink-line-printed square). The weave of the nest is rendered as fine radial strokes. Background is cool stone-paper (#eef0f4), not white. Bird is NOT in this image — just the nest as the subject. Restrained palette: paper, ink, single cobalt accent (used sparingly on one paper edge), single gold (the central bead). The gold bead is rendered FLAT (no spherical highlight, no 3D shading). No gradients, no glow. Centered composition. Editorial restraint, like a botanist's specimen plate of a found object. Craftsmanship register. Strict minimalism — only the nest, the bead, and three HTML papers. Nothing else in the composition. No decorative elements in any corner.`,
  },
  {
    id: "P04",
    title: "Master skill illustration",
    status: "pending",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/p04-master.png",
    prompt: `A vintage natural-history monograph plate showing an open hand-bound book or scroll, hairline-engraved style. The book is open at the center of the composition, pages visible with faint horizontal text-lines printed in mid-gray. A quill or feather rests diagonally across the binding, its tip pointing down-left. The quill has a single deep cobalt accent (#1f2b80) along its shaft and a single mustard-gold tip detail (#d4a233). One small woven nest is suggested faintly in the lower-right corner of the composition as marginalia — this is a study book that teaches the bird. Background is cool stone-paper (#eef0f4). Restrained palette: paper, ink, one cobalt, one gold. No gradients. Flat engraving aesthetic. Editorial composition. The book is the focus; the nest is a faint corner reference. No human figure. No hands. Only the book, the quill, and the suggested nest corner. No decorative elements anywhere except the suggested nest marginalia.`,
  },
  {
    id: "P05",
    title: "OG social card (launch hero)",
    status: "pending",
    size: "2048x1152",
    quality: "high",
    save_path: ".tmp-brand-assets/p05-og-v2.png",
    prompt: `A vintage natural-history monograph plate engraved in flat geometric style. Composition: left two-thirds is intentionally blank cool stone-paper (#eef0f4) for overlay text. Right third shows a single magpie perched on the rim of a woven nest. The nest sits at the right edge of the composition; inside the nest are two or three folded paper rectangles (HTML pages with actual readable HTML markup like <html> <head> <body> tags) and one prominent mustard-gold shiny bead (#d4a233). The bird's head is turned slightly toward the camera, looking at the viewer. Deep ink-black plumage with naturalistic white belly markings. One deep cobalt blue wing patch (#1f2b80) clearly visible. Restrained palette: paper, ink, cobalt, gold. No gradients. Hairline wood-engraving detail. Optional: faint code-text marginalia along the lower-left edge (very subtle, like a manuscript margin annotation). 16:9 aspect ratio (or wider). Composition leaves clear negative space on the left two-thirds for text overlay. Craftsmanship register. No decorative elements in any corner. No diamond / gem / sparkle marginalia.`,
  },
  {
    id: "P06",
    title: "Field Index paper texture",
    status: "pending",
    size: "2048x2048",
    quality: "high",
    save_path: ".tmp-brand-assets/p06-paper-texture.png",
    prompt: `A subtle cool stone-paper texture in the spirit of well-kept vintage monograph endpapers. Base color is #eef0f4 (cool stone, never pure white). Texture is extremely subtle: very faint fiber lines, occasional very faint hairline foxing marks scattered sparsely. No images, no figures, no symbols — pure texture only. No central focus — uniformly distributed so it tiles seamlessly when repeated. No grain noise that pixelates — soft, painterly paper feel. Designed to sit BEHIND text and illustrations without competing. Contrast minimum so body text remains fully readable on top. 2048×2048 square. Tileable. Edges fade to perfect match for seamless tiling, no edge discontinuity.`,
  },
  {
    id: "M01",
    title: "Magpie mark square (logo / favicon)",
    status: "new",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/m01-mark-square.png",
    prompt: `A single magpie shown in three-quarter side view, perched on a thin horizontal branch line. Vintage natural-history monograph engraving in the spirit of Audubon and Thomas Bewick. Bird is centered in a 1:1 square composition with generous negative space on all four sides. Deep ink-black plumage with naturalistic white belly markings (real magpie). One visible wing carries a single deep cobalt blue patch (#1f2b80) — clean panel, not a glint or sparkle. A single mustard-gold dot (#d4a233) is visible NEAR THE BEAK (just in front of it) — this is the brand bead, distinct from the eye. The bead is rendered flat (no spherical highlight). Background is cool stone-paper (#eef0f4), never white. Hairline wood-engraving feather detail throughout. Craftsmanship register — looks like it took weeks to engrave. Restrained three-color palette: paper, ink, cobalt, gold. No gradients. No glow. Centered subject. 1:1 square. Intended use: brand logo · favicon source · social avatar — the bird must read clearly at small sizes. No decorative elements in any corner. No diamond / gem / sparkle marginalia. No background pattern. Single bird on simple branch line, that is the whole composition.`,
  },
  {
    id: "M02",
    title: "Nest icon square (Nest actor)",
    status: "new",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/m02-nest-icon.png",
    prompt: `A simple top-down view of a circular woven nest, vintage natural-history monograph engraving in the spirit of Audubon and Thomas Bewick. Inside the nest: one prominent mustard-gold shiny bead (#d4a233) at the exact center, rendered FLAT (no 3D shading, no spherical highlight, no glow). The weave of the nest is rendered as fine radial strokes — hairline detail. Composition is much simpler than a full plate — this is an icon: just the nest from above, the bead, nothing else. No HTML papers inside, no leaves around the nest, no marginalia, no branches. Background is cool stone-paper (#eef0f4), never white. 1:1 square. Centered subject. Generous negative space all four sides. Restrained palette: paper, ink, gold. No cobalt in this version. No gradients. Craftsmanship register. Intended use: Nest actor icon · small UI symbol · favicon variant. Must read clearly at small sizes. No decorative elements in any corner. No diamond / gem / sparkle marginalia anywhere on the canvas.`,
  },
  {
    id: "M03",
    title: "Master scroll icon (Master actor)",
    status: "new",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/m03-master-icon.png",
    prompt: `A simple open hand-bound book centered in a 1:1 square composition, vintage natural-history monograph engraving in the spirit of Audubon and Thomas Bewick. The book is open with both pages visible — pages mostly blank with faint horizontal text-lines printed in mid-gray on each page. A single quill rests diagonally across the binding, its tip pointing down-left. The quill shaft is deep cobalt (#1f2b80), the feather tip is mustard-gold (#d4a233). Composition is simpler than a full plate — this is an icon: just the book, the quill, nothing else. No nest marginalia, no human figure, no hands, no decorations, no background pattern. Background is cool stone-paper (#eef0f4), never white. Centered subject. Generous negative space all four sides. 1:1 square. Hairline engraving detail. Craftsmanship register. Restrained palette: paper, ink, cobalt, gold. No gradients. Intended use: Master actor icon · Skill docs symbol · onboarding glyph. Must read clearly at small sizes. No decorative elements in any corner. No diamond / gem / sparkle marginalia anywhere on the canvas.`,
  },
  {
    id: "LOGO-A",
    title: "Logo variant A — V4-faithful retake (three-quarter, tail-down)",
    status: "new",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/logo-A-v4-faithful.png",
    prompt: `A single magpie shown in three-quarter side view, beak up-tilted at a slight upward angle, no branch and no perch — the bird floats centered in the composition as a clean isolated mark. Vintage natural-history monograph engraving in the spirit of Audubon and Thomas Bewick. Bird fills most of the frame (tight crop, modest equal negative space on all four sides). Deep ink-black plumage with naturalistic white belly markings (real Eurasian magpie). The bird's body angles slightly down-right, with the long tail extending toward the lower-right at approximately 25 degrees below horizontal. One visible wing carries a single deep cobalt blue patch (#1f2b80) shaped as a defined angular panel of color — NOT a glint, NOT a sparkle, NOT a feather highlight — a clean intentional cobalt shape on the wing. A single mustard-gold dot (#d4a233) is positioned JUST IN FRONT OF THE BEAK — this is the brand bead, distinct from the eye, sitting outside the bird's body. The bead is rendered FLAT (no spherical highlight, no glow, no 3D shading). Background is cool stone-paper (#eef0f4), never white. Hairline wood-engraving feather detail throughout. Craftsmanship register — looks like it took weeks to engrave. Restrained four-color palette only: paper, ink-black, cobalt, gold. No gradients. No glow. Centered subject. 1:1 square composition. Intended use: production logo · favicon master · social avatar — the bird must read clearly at 32×32 favicon scale. No branch. No perch. No ground line. No decorative elements anywhere. No diamond / gem / sparkle marginalia. No background pattern. Single bird silhouette as a clean isolated mark on paper.`,
  },
  {
    id: "LOGO-B",
    title: "Logo variant B — clean side profile (heraldic mark)",
    status: "new",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/logo-B-side-profile.png",
    prompt: `A single magpie shown in a clean full side profile, body horizontal, head level, beak pointing forward (to the right). The bird stands stationary with feet implied (no visible branch or ground — feet hidden behind a hairline horizontal baseline that anchors but does not decorate). Vintage natural-history monograph engraving in the spirit of Audubon and Thomas Bewick, but with an iconic heraldic register — think coat-of-arms bird or vintage coin face. Bird fills the horizontal width of the frame with modest negative space top and bottom. Deep ink-black plumage with naturalistic white belly markings (real Eurasian magpie). The visible wing folded against the body carries a single deep cobalt blue panel (#1f2b80) — a clean angular shape, not a glint. A single mustard-gold dot (#d4a233) is positioned JUST IN FRONT OF THE BEAK — flat, no highlight, no glow — the brand bead. The bird's eye is rendered as a small ink dot, distinct from the gold bead. The long tail extends straight back behind the body, mostly horizontal with a slight downward droop. Background is cool stone-paper (#eef0f4), never white. Hairline wood-engraving feather detail throughout. Craftsmanship register. Restrained four-color palette only: paper, ink-black, cobalt, gold. No gradients. No glow. 1:1 square composition. Intended use: production logo · favicon · social avatar — must read clearly at 32×32 favicon scale. No decorative elements anywhere. No diamond / gem / sparkle marginalia. No background pattern. Clean iconic profile silhouette as the entire composition.`,
  },
  {
    id: "LOGO-C",
    title: "Logo variant C — bust portrait (favicon-first, head + chest)",
    status: "new",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/logo-C-bust-portrait.png",
    prompt: `A tight bust portrait of a single magpie — head and upper chest only, body cropped at the shoulder line. Three-quarter facing toward the viewer, head turned slightly so both eyes are partially visible but the strong-side eye reads clearly. Vintage natural-history monograph engraving in the spirit of Audubon and Thomas Bewick. Composition fills the frame: the head and upper chest occupy most of the 1024×1024 canvas with only modest negative space at the corners. Deep ink-black plumage on the head and back-of-neck with the white belly-and-cheek markings starting at the lower chest (real Eurasian magpie coloration). One visible shoulder-of-wing carries a single deep cobalt blue panel (#1f2b80) — clean angular shape, not a glint. A single mustard-gold dot (#d4a233) is positioned JUST IN FRONT OF THE BEAK — flat, no highlight — the brand bead. The eye is rendered as a small ink dot ringed by a hairline pale circle, clearly distinct from the gold bead. Beak slightly open, alert posture. Background is cool stone-paper (#eef0f4), never white. Hairline wood-engraving feather detail throughout — especially the head and cheek feathers. Craftsmanship register. Restrained four-color palette only: paper, ink-black, cobalt, gold. No gradients. No glow. 1:1 square composition. Intended use: production logo · favicon master · social avatar — designed favicon-first; must read clearly at 16×16 and 32×32 scale where a full-body bird would lose detail. No branch. No body below shoulder. No decorative elements anywhere. No diamond / gem / sparkle marginalia. No background pattern. Clean head-and-shoulders mark as the entire composition.`,
  },
  {
    id: "M04",
    title: "Bird in flight silhouette",
    status: "new",
    size: "1024x1024",
    quality: "high",
    save_path: ".tmp-brand-assets/m04-bird-silhouette.png",
    prompt: `A single magpie in flight, side profile, wings fully spread in full glide. Vintage natural-history monograph engraving in the spirit of Audubon and Thomas Bewick. Bird is silhouette-strong against the cool stone-paper background — high contrast but still hairline-engraved (not solid black, retain feather detail). Same bird character as the rendered pose variants: deep ink-black plumage with naturalistic white belly markings, one deep cobalt blue wing patch (#1f2b80), one mustard-gold dot (#d4a233) near the beak. The bird is NOT carrying anything in this version — clean silhouette, beak forward, wings extended in full glide. No HTML page, no scroll, no object in the beak. Background is cool stone-paper (#eef0f4), never white. 1:1 square. Centered subject. Generous negative space all four sides. Restrained palette: paper, ink, cobalt, gold. No gradients. Craftsmanship register. Intended use: animation backplate · header chrome bird · in-running text accent · footer mark. Must read clearly at small sizes AND large sizes. No decorative elements in any corner. No diamond / gem / sparkle marginalia anywhere on the canvas.`,
  },
];
