#!/usr/bin/env node
// v0.9.2 Phase D / D6 — 1K-visual benchmark fixture.
//
// Seeds $MAGPIE_HOME with: 20 projects, 50 visuals each (1000 total),
// 1-5 versions per visual (skewed low), 3-8 tags from a 30-tag pool,
// 5% archived, 8% starred. Idempotent (skips if marker present).
//
// Used by:
//   - Phase D / D3 — find_visuals EXPLAIN QUERY PLAN at 1K
//   - Phase J / J1 — find_visuals headroom @ 10K (--count=10000)
//
// Tarball allowlist (Phase B/S1) excludes scripts/ — Owner never sees this.
//
// Usage:
//   MAGPIE_HOME=/path node scripts/seed-bench.mjs              # seed @ 1000 (default)
//   MAGPIE_HOME=/path node scripts/seed-bench.mjs --reset      # wipe seeded rows + re-seed
//   MAGPIE_HOME=/path node scripts/seed-bench.mjs --json       # machine-readable summary
//   MAGPIE_HOME=/path node scripts/seed-bench.mjs --count=10000 # Phase J / J1 headroom run

import Database from "better-sqlite3";
import { customAlphabet } from "nanoid";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const MIGRATIONS_DIR = join(REPO_ROOT, "src", "store", "migrations");

const SEED_MARKER_KEY = "seed_bench_marker";
const SEED_PROJECT_PREFIX = "seed-bench-";

const ID_ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const newId = customAlphabet(ID_ALPHABET, 12);
const nowIso = () => new Date().toISOString();

const PROJECT_TYPES = ["mockup", "diagram", "mixed"];
const VISUAL_TYPES = ["html", "mermaid", "svg", "markdown", "dot", "vega-lite", "d2"];
const SOURCES = [null, "claude", "manual", "stitch", "figma"];

const TAG_POOL = [
  "wip", "final", "approved", "review", "blocked", "hot", "cool",
  "auth", "billing", "dashboard", "settings", "onboarding", "checkout",
  "mobile", "desktop", "a11y", "dark-mode", "v2", "v3", "draft",
  "hero", "footer", "nav", "pricing", "table", "form", "modal",
  "chart", "diagram", "icon",
];

const TITLE_PARTS_A = [
  "auth", "billing", "dashboard", "settings", "onboarding", "checkout",
  "pricing", "hero", "footer", "nav", "modal", "table", "form", "chart",
];
const TITLE_PARTS_B = [
  "flow", "screen", "view", "panel", "card", "row", "grid", "list",
  "detail", "summary", "header", "wizard", "stepper",
];
const TITLE_SUFFIXES = ["v1", "v2", "v3", "draft", "final", "wip", "alpha", "beta"];

const SVG_STUB = '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="80"><rect width="120" height="80" fill="#f3ece0"/></svg>';
const STUBS = {
  html: '<!doctype html><meta charset="utf-8"><title>seed</title><div style="font-family:system-ui;padding:24px">Seed stub.</div>',
  mermaid: "graph TD\n  A[seed]-->B[stub]",
  svg: SVG_STUB,
  markdown: "# Seed stub\n\nGenerated by `scripts/seed-bench.mjs`.\n",
  dot: 'digraph { A -> B; A [label="seed"]; }',
  "vega-lite": JSON.stringify({
    $schema: "https://vega.github.io/schema/vega-lite/v5.json",
    data: { values: [{ a: 1, b: 2 }] },
    mark: "bar",
    encoding: { x: { field: "a" }, y: { field: "b" } },
  }),
  d2: "seed -> stub",
};

function extFor(type) {
  if (type === "html") return "html";
  if (type === "mermaid") return "mmd";
  if (type === "markdown") return "md";
  if (type === "dot") return "dot";
  if (type === "vega-lite") return "vl.json";
  if (type === "d2") return "d2";
  return "svg";
}

function resolveHome() {
  return process.env.MAGPIE_HOME ?? join(homedir(), ".magpie");
}

function ensureDirs(home) {
  if (!existsSync(home)) mkdirSync(home, { recursive: true });
  const blobs = join(home, "blobs");
  if (!existsSync(blobs)) mkdirSync(blobs, { recursive: true });
  return blobs;
}

function runMigrations(db) {
  const current = (() => {
    try {
      const row = db.prepare("SELECT value FROM meta WHERE key = 'schema_version'").get();
      return row ? Number(row.value) : 0;
    } catch {
      return 0;
    }
  })();
  const files = readdirSync(MIGRATIONS_DIR).filter((f) => f.endsWith(".sql")).sort();
  for (const file of files) {
    const num = Number(file.split("_")[0]);
    if (Number.isNaN(num) || num <= current) continue;
    db.exec(readFileSync(join(MIGRATIONS_DIR, file), "utf8"));
  }
}

// Deterministic RNG so seeded data is reproducible across runs.
function mulberry32(seed) {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(42);
const pick = (arr) => arr[Math.floor(rand() * arr.length)];
const between = (lo, hi) => lo + Math.floor(rand() * (hi - lo + 1));

function versionCountSkewed() {
  const r = rand();
  if (r < 0.5) return 1;
  if (r < 0.75) return 2;
  if (r < 0.9) return 3;
  if (r < 0.97) return 4;
  return 5;
}

function generateTitle(i) {
  return `${pick(TITLE_PARTS_A)}-${pick(TITLE_PARTS_B)}-${pick(TITLE_SUFFIXES)}-${i}`;
}

function pickUniqueTags(min, max) {
  const n = between(min, max);
  const picked = new Set();
  while (picked.size < n) picked.add(pick(TAG_POOL));
  return [...picked];
}

function resetSeed(db, blobsRoot) {
  const seededVisualIds = db
    .prepare(
      `SELECT v.id AS id FROM visuals v
        JOIN projects p ON p.id = v.project_id
       WHERE p.name LIKE ?`
    )
    .all(`${SEED_PROJECT_PREFIX}%`)
    .map((r) => r.id);

  // FK cascade kills visuals + versions + visual_tags when projects go.
  const tx = db.transaction(() => {
    db.prepare("DELETE FROM projects WHERE name LIKE ?").run(`${SEED_PROJECT_PREFIX}%`);
    db.prepare("DELETE FROM tags WHERE name LIKE ?").run("seed-bench-tag-%");
    db.prepare("DELETE FROM meta WHERE key = ?").run(SEED_MARKER_KEY);
  });
  tx();

  let blobsRemoved = 0;
  for (const id of seededVisualIds) {
    const dir = join(blobsRoot, id);
    if (existsSync(dir)) {
      rmSync(dir, { recursive: true, force: true });
      blobsRemoved++;
    }
  }
  return { rowsRemoved: seededVisualIds.length, blobsRemoved };
}

function readMarker(db) {
  const row = db.prepare("SELECT value FROM meta WHERE key = ?").get(SEED_MARKER_KEY);
  return row ? row.value : null;
}

function seed(db, blobsRoot, totalVisuals) {
  // v0.9.2 Phase J / J1 — variable scale via --count. Projects fixed at 20;
  // visuals-per-project scales linearly. 1000 (default) -> 50/proj; 10000 -> 500/proj.
  const PROJECT_COUNT = 20;
  const VISUALS_PER_PROJECT = Math.ceil(totalVisuals / PROJECT_COUNT);
  const MIN_TAGS = 3;
  const MAX_TAGS = 8;
  const ARCHIVED_PCT = 0.05;
  const STARRED_PCT = 0.08;

  // Tag pool — namespace with seed-bench- prefix so --reset can scope cleanup
  // without touching Owner tags. visual_tags links by tag id, not name, so
  // display label is decoupled from the lookup key.
  const tagIdByName = new Map();
  const insertTag = db.prepare("INSERT OR IGNORE INTO tags (id, name, color) VALUES (?, ?, NULL)");
  const selectTag = db.prepare("SELECT id FROM tags WHERE name = ?");
  for (const name of TAG_POOL) {
    const nsName = `seed-bench-tag-${name}`;
    const id = newId();
    insertTag.run(id, nsName);
    const row = selectTag.get(nsName);
    tagIdByName.set(name, row.id);
  }

  const insertProject = db.prepare(
    "INSERT INTO projects (id, name, type, description, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)"
  );
  const insertVisual = db.prepare(
    `INSERT INTO visuals
      (id, project_id, title, type, source, description, current_ver, starred, created_at, updated_at, archived_at)
     VALUES (?, ?, ?, ?, ?, NULL, ?, ?, ?, ?, ?)`
  );
  const insertVersion = db.prepare(
    `INSERT INTO versions
      (id, visual_id, version_num, content_path, thumb_path, render_status, render_error, message, description, created_at)
     VALUES (?, ?, ?, ?, NULL, 'ok', NULL, ?, NULL, ?)`
  );
  const insertVisualTag = db.prepare(
    "INSERT OR IGNORE INTO visual_tags (visual_id, tag_id) VALUES (?, ?)"
  );

  const startedAt = Date.now();
  let visualsInserted = 0;
  let versionsInserted = 0;
  let blobBytes = 0;

  const tx = db.transaction(() => {
    for (let p = 0; p < PROJECT_COUNT; p++) {
      const projectId = newId();
      const now = nowIso();
      const projectName = `${SEED_PROJECT_PREFIX}${String(p).padStart(2, "0")}-${pick(TITLE_PARTS_A)}`;
      insertProject.run(projectId, projectName, pick(PROJECT_TYPES), null, now, now);

      for (let v = 0; v < VISUALS_PER_PROJECT; v++) {
        const visualId = newId();
        const type = pick(VISUAL_TYPES);
        const source = pick(SOURCES);
        const versionCount = versionCountSkewed();
        const starred = rand() < STARRED_PCT ? 1 : 0;
        const archivedAt = rand() < ARCHIVED_PCT ? nowIso() : null;
        const title = generateTitle(v);

        insertVisual.run(
          visualId,
          projectId,
          title,
          type,
          source,
          versionCount,
          starred,
          now,
          now,
          archivedAt
        );
        visualsInserted++;

        const visualBlobDir = join(blobsRoot, visualId);
        if (!existsSync(visualBlobDir)) mkdirSync(visualBlobDir, { recursive: true });

        for (let n = 1; n <= versionCount; n++) {
          const versionId = newId();
          const ext = extFor(type);
          const content = STUBS[type] ?? STUBS.html;
          const blobPath = join(visualBlobDir, `v${n}.${ext}`);
          writeFileSync(blobPath, content, "utf8");
          blobBytes += Buffer.byteLength(content, "utf8");
          insertVersion.run(versionId, visualId, n, blobPath, null, nowIso());
          versionsInserted++;
        }

        for (const tagName of pickUniqueTags(MIN_TAGS, MAX_TAGS)) {
          insertVisualTag.run(visualId, tagIdByName.get(tagName));
        }
      }
    }

    db.prepare("INSERT OR REPLACE INTO meta (key, value) VALUES (?, ?)").run(
      SEED_MARKER_KEY,
      nowIso()
    );
  });
  tx();

  return {
    projectsInserted: PROJECT_COUNT,
    visualsInserted,
    versionsInserted,
    tagsInserted: TAG_POOL.length,
    blobBytes,
    elapsedMs: Date.now() - startedAt,
  };
}

function parseCount(argv) {
  // v0.9.2 Phase J / J1 — `--count=N` flag. Default 1000 preserves the contract
  // existing find-visuals-bench.test.ts relies on. Gentle ceiling 100000 guards
  // against accidental --count=1000000 typos blowing the dev laptop wall.
  for (const a of argv) {
    if (a.startsWith("--count=")) {
      const v = Number(a.slice("--count=".length));
      if (!Number.isFinite(v) || !Number.isInteger(v) || v < 1) {
        throw new Error(`[seed-bench] --count must be a positive integer, got ${a}`);
      }
      if (v > 100000) {
        throw new Error(`[seed-bench] --count must be <= 100000 (got ${v})`);
      }
      return v;
    }
  }
  return 1000;
}

function main() {
  const argv = process.argv.slice(2);
  const args = new Set(argv);
  const wantReset = args.has("--reset");
  const wantJson = args.has("--json");
  const totalVisuals = parseCount(argv);

  const home = resolveHome();
  const blobsRoot = ensureDirs(home);
  const dbPath = join(home, "db.sqlite");

  const db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  db.pragma("foreign_keys = ON");
  runMigrations(db);

  let resetSummary = null;
  if (wantReset) {
    resetSummary = resetSeed(db, blobsRoot);
  }

  const existing = readMarker(db);
  if (existing && !wantReset) {
    const summary = {
      status: "skipped",
      reason: "seed marker already present; pass --reset to re-seed",
      marker: existing,
      home,
    };
    db.close();
    if (wantJson) {
      console.log(JSON.stringify(summary, null, 2));
    } else {
      console.log(`[seed-bench] already seeded at ${existing} — pass --reset to re-seed`);
    }
    return;
  }

  const result = seed(db, blobsRoot, totalVisuals);
  db.close();

  const summary = {
    status: "ok",
    home,
    reset: resetSummary,
    targetCount: totalVisuals,
    ...result,
  };

  if (wantJson) {
    console.log(JSON.stringify(summary, null, 2));
    return;
  }

  console.log(`[seed-bench] home          ${home}`);
  console.log(`[seed-bench] target        ${totalVisuals} visuals`);
  if (resetSummary) {
    console.log(`[seed-bench] reset         ${resetSummary.rowsRemoved} visuals · ${resetSummary.blobsRemoved} blob dirs`);
  }
  console.log(`[seed-bench] projects      ${result.projectsInserted}`);
  console.log(`[seed-bench] visuals       ${result.visualsInserted}`);
  console.log(`[seed-bench] versions      ${result.versionsInserted}`);
  console.log(`[seed-bench] tags          ${result.tagsInserted}`);
  console.log(`[seed-bench] blob bytes    ${result.blobBytes.toLocaleString()}`);
  console.log(`[seed-bench] elapsed       ${result.elapsedMs} ms`);
}

main();
